name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          3.1.x
          6.0.x
        
    - name: Restore dependencies
      run: dotnet restore Customer/Customer.sln
      
    - name: Build
      run: dotnet build --no-restore Customer/Customer.sln
      
    - name: Test
      run: dotnet test Customer/Customer.sln --configuration Debug --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Codecov upload 
      uses: codecov/codecov-action@v3
